/* --Актуальная таблица и поля, как в БД и в Entity*/
DROP  TABLE Person CASCADE ;
/*--удалить все данные из таблицы*/
TRUNCATE TABLE Person;

CREATE TABLE person(
    id int GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY ,
    fio varchar(100) NOT NULL UNIQUE ,
    yearOfBirth int check ( yearOfBirth < 2100 and yearOfBirth >= 1900) NOT NULL
);

INSERT INTO person(fio, yearOfBirth) VALUES ('Александра Б',1984);
INSERT INTO person(fio, yearOfBirth) VALUES ('Edvard М',1980);
INSERT INTO person(fio, yearOfBirth) VALUES ( 'Evgeny Ж', 1991);
INSERT INTO person(fio, yearOfBirth) VALUES ( 'Egor Р', 1991);
INSERT INTO person(fio, yearOfBirth) VALUES ( 'Михаил С', 1991);
INSERT INTO person(fio, yearOfBirth) VALUES ( 'Виталий Н', 1985);
INSERT INTO person(fio, yearOfBirth) VALUES ( 'Наталья П', 1991);
INSERT INTO person(fio, yearOfBirth) VALUES ( 'Аннастасия К', 1995);
INSERT INTO person(fio, yearOfBirth) VALUES ( 'Артем Д', 1991);
INSERT INTO person(fio, yearOfBirth) VALUES ( 'Сергей Н', 1970);
