# Этот файл для теста и работы, поля м.б. не достоверны

DROP  TABLE Person CASCADE ;
# --удалить все данные из таблицы
TRUNCATE TABLE Person CASCADE ;

# --Добавить столбец в таблицу
ALTER TABLE person ADD  COLUMN address varchar(50) NOT NULL ;
ALTER TABLE person ADD  COLUMN email varchar(50) NOT NULL UNIQUE;

CREATE TABLE person(
    id int GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY ,
    fio varchar(100) NOT NULL UNIQUE ,
    yearOfBirth int check ( yearOfBirth < 2100 and yearOfBirth >= 1900) NOT NULL
);

INSERT INTO person(fio, yearOfBirth) VALUES ('Александра',1984);
INSERT INTO person(fio, yearOfBirth) VALUES ('Edvard',1980);
INSERT INTO person(fio, yearOfBirth) VALUES ( 'Evgeny', 1991);
INSERT INTO person(fio, yearOfBirth) VALUES ( 'Egor ', 1991);
INSERT INTO person(fio, yearOfBirth) VALUES ( 'Михаил', 1991);
INSERT INTO person(fio, yearOfBirth) VALUES ( 'Виталий', 1985);
INSERT INTO person(fio, yearOfBirth) VALUES ( 'Наталья', 1991);
INSERT INTO person(fio, yearOfBirth) VALUES ( 'Аннастасия', 1995);
INSERT INTO person(fio, yearOfBirth) VALUES ( 'Артем', 1991);
INSERT INTO person(fio, yearOfBirth) VALUES ( 'Сергей', 1970);

INSERT INTO person(fio, yearOfBirth, email,number_phone) VALUES ('Александра Б',1984,'alexa@mail.rub', '+375447798748');
INSERT INTO person(fio, yearOfBirth, email,number_phone) VALUES ('Edvard M',1980,'edvard@mail.rub', '+375447798749');
INSERT INTO person(fio, yearOfBirth, email,number_phone) VALUES ('Egor',1991,'egor@mail.rub', '+375447798747');
INSERT INTO person(fio, yearOfBirth, email,number_phone) VALUES ('Михаил С',1991,'miha@mail.rub', '+375447798748');
INSERT INTO person(fio, yearOfBirth, email,number_phone) VALUES ('Наталья',1984,'nata@mail.rub', '+375447798748');
INSERT INTO person(fio, yearOfBirth, email,number_phone) VALUES ('Алеся Б',1984,'ak_rb1@mail.ru', '+375447798748');
INSERT INTO person(fio, yearOfBirth, email,number_phone) VALUES ('Александра Б',1984,'alexa6@mail.rub', '+375447798748');




SELECT *FROM person;

SELECT fio FROM person WHERE id=1;