/* --Актуальная таблица и поля, как в БД и в Entity*/
DROP  TABLE Person CASCADE;
/*--удалить все данные из таблицы*/
TRUNCATE TABLE Person;

CREATE TABLE person(
    id int GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY ,
    fio varchar(100) NOT NULL,
    yearOfBirth int check ( yearOfBirth < 2100 and yearOfBirth >= 1900) NOT NULL,
    email varchar(50) NOT NULL UNIQUE,
    number_phone varchar(50) NOT NULL,
    created_at timestamp default current_timestamp,
    updated_at  timestamp default current_timestamp
);

INSERT INTO person(fio, yearOfBirth, email,number_phone) VALUES ('Александра Б',1984,'alexa@mail.rub', '+375447798748');
INSERT INTO person(fio, yearOfBirth, email,number_phone) VALUES ('Edvard M',1980,'edvard@mail.rub', '+375447798749');
INSERT INTO person(fio, yearOfBirth, email,number_phone) VALUES ('Egor',1991,'egor@mail.rub', '+375447798747');
INSERT INTO person(fio, yearOfBirth, email,number_phone) VALUES ('Михаил С',1991,'miha@mail.rub', '+375447798748');
INSERT INTO person(fio, yearOfBirth, email,number_phone) VALUES ('Наталья',1984,'nata@mail.rub', '+375447798748');
INSERT INTO person(fio, yearOfBirth, email,number_phone) VALUES ('Алеся Б',1984,'ak_rb1@mail.ru', '+375447798748');
INSERT INTO person(fio, yearOfBirth, email,number_phone) VALUES ('Александра Б',1984,'alexa6@mail.rub', '+375447798748');

